version: "3.7"

services:
  smoldb-0:
    image: kshivendu/smoldb:latest
    ports:
      - "9001:9900"
      - "5001:9920"
    entrypoint: []
    command: ./smoldb

  smoldb-1:
    image: kshivendu/smoldb:latest
    depends_on:
      - smoldb-0
    ports:
      - "9002:9900"
      - "5002:9920"
    entrypoint: []
    command: sh -c "sleep 5 && ./smoldb --bootstrap 'http://smoldb-0:9900'" # this http:// part is important for bootstrap (might eventually fix)

  smoldb-2:
    image: kshivendu/smoldb:latest
    depends_on:
      - smoldb-0
    ports:
      - "9003:9900"
      - "5003:9920"
    entrypoint: []
    command: sh -c "sleep 6 && ./smoldb --bootstrap 'http://smoldb-0:9900'"
