version: "3.7"

services:
  smoldb-0:
    image: ghcr.io/kshivendu/smoldb:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__RESHARDING_ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    ports:
      - "9001:9000"
    entrypoint: []
    command: ./smoldb --url 'smoldb-0:9000'

  smoldb-1:
    image: ghcr.io/kshivendu/smoldb:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__RESHARDING_ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    depends_on:
      - smoldb-0
    ports:
      - "9002:9000"
    entrypoint: []
    command: bash -c "sleep 5 && ./smoldb --bootstrap 'smoldb-0:5000' --url 'smoldb-1:9000'"

  smoldb-2:
    image: ghcr.io/kshivendu/smoldb:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__RESHARDING_ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    depends_on:
      - smoldb-0
    ports:
      - "9003:9000"
    entrypoint: []
    command: bash -c "sleep 5 && ./smoldb --bootstrap 'smoldb-0:5000' --url 'smoldb-2:9000'"
