version: "3.7"

services:
  smoldb-node-0:
    image: kshivendu/smoldb:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__RESHARDING_ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    ports:
      - "9900:9900"
      - "9910:9910"
    command: ./smoldb --uri 'http://smoldb-node-0:9920'

  smoldb-node-1:
    image: kshivendu/smoldb:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__RESHARDING_ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    depends_on:
      - smoldb-node-0
    ports:
      - "9901:9900"
      - "9911:9910"
    command: bash -c "sleep 5 && ./smoldb --bootstrap 'http://smoldb-node-0:9920' --uri 'http://smoldb-node-1:9920'"

  smoldb-node-2:
    image: kshivendu/smoldb:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__CLUSTER__ENABLED=true
      - QDRANT__CLUSTER__RESHARDING_ENABLED=true
      - QDRANT__CLUSTER__P2P__PORT=6335
    depends_on:
      - smoldb-node-0
    ports:
      - "9902:9900"
      - "9912:9910"
    command: bash -c "sleep 6 && ./smoldb --bootstrap 'http://smoldb-node-0:9920' --uri 'http://smoldb-node-2:9920'"
